apiVersion: v1
description: Helm chart for creating and populating a new environment at wiremind
name: environment
type: application
version: 0.1.0
appVersion: "0.1.0"
home: https://github.com/wiremind/wiremind-helm-charts/tree/main/charts/environment
sources:
  - https://github.com/wiremind/wiremind-helm-charts/tree/main/charts/environment
keywords:
  - environment
  - infra
maintainers:
  - name: Wiremind
    url: https://github.com/wiremind/wiremind-helm-charts
