apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "chartreuse.serviceAccountName" . }}
  labels:
    {{- include "chartreuse.labels" . | nindent 4 }}
  {{- with (include "chartreuse.dependencyAnnotations" .) }}
  annotations:
    {{- . | nindent 4 }}
  {{- end }}