apiVersion: v1
appVersion: v0.61.1.x
description: The easy, open source way for everyone in your company to ask questions and learn from data.
home: http://www.metabase.com/
icon: http://www.metabase.com/images/logo.svg
maintainers:
- email: phamminhthanh69@gmail.com
  name: pmint93
name: metabase
sources:
- https://github.com/metabase/metabase
version: 2.27.5
