{{- if .Values.clusterSecretStore.enabled -}}

apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: {{ include "platform-namespace-core.cluster-secret-store.name" $ }}
  labels:
    {{- include "platform-namespace-core.labels" $ | nindent 4 }}
spec:
  provider:
    {{- if eq $.Values.clusterSecretStore.provider.name "infisical" }}
    {{- $infisicalConfig := $.Values.clusterSecretStore.provider }}
    infisical:
      auth:
        universalAuthCredentials:
          clientId:
            key: clientId
            name: {{ $infisicalConfig.secretName | quote }}
            namespace: {{ $infisicalConfig.secretNamespace | quote }}
          clientSecret:
            key: clientSecret
            name: {{ $infisicalConfig.secretName | quote }}
            namespace: {{ $infisicalConfig.secretNamespace | quote }}
      hostAPI: {{ $.Values.clusterSecretStore.provider.hostAPI | quote }}
      secretsScope:
        projectSlug: {{ $infisicalConfig.projectSlug | quote }}
        environmentSlug: {{ $infisicalConfig.environmentSlug | quote }}
        recursive: true
        secretsPath: {{ $infisicalConfig.secretsPath | quote }}
    {{- else }}
    {{ fail (printf "Unsupported external secrets provider: %s. Only 'infisical' is currently supported" $.Values.clusterSecretStore.provider.name) }}
    {{- end }}
  conditions:
    {{- if eq $.Values.namespace.labels.project "platform" }}
    - namespaces:
      - {{ $.Release.Name | quote }}
    {{- else }}
    - namespaceSelector:
        matchLabels:
          {{- range $key, $value := $.Values.namespace.labels }}
          {{ $key }}: {{ $value | quote }}
          {{- end }}
    {{- end }}

{{- end -}}
