{{ if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "postgres-operator.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "postgres-operator.labels" . | nindent 4 }}
    app.kubernetes.io/instance: {{ .Release.Name }}
{{ end }}
