{{- if not .Values.secret.existingSecret }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "openstack-exporter.fullname" . }}-config
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "openstack-exporter.labels" . | nindent 4 }}
type: Opaque
stringData:
  clouds.yaml: |
{{ .Values.clouds_yaml_config | indent 4 }}
{{- end }}
