---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "openstack-exporter.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "openstack-exporter.labels" . | nindent 4 }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  {{- if eq .Values.service.type "ClusterIP" }}
  clusterIP: None
  {{- end }}
  ports:
    - name: metrics
      port: {{ .Values.service.port }}
      targetPort: metrics
      protocol: TCP
  selector:
    {{- include "openstack-exporter.selectorLabels" . | nindent 4 }}
