name: Compliance

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  commit:
    name: Commit
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          fetch-depth: 0

      - name: Conventional commit check
        uses: cocogitto/cocogitto-action@c7a74f5406bab86da17da0f0e460a69f8219a68c # v3.11.0
