name: Renovate

on:
  pull_request:
    branches:
      - main
    paths:
      - renovate.json
      - .github/workflows/renovate.yml
  push:
    branches:
      - main
    paths:
      - renovate.json
      - .github/workflows/renovate.yml
jobs:
  validate:
    name: Validate Renovate Config
    runs-on: ubuntu-24.04
    permissions:
      contents: read
    container:
      image: ghcr.io/renovatebot/renovate:44
      options: --user 0
    steps:
      - name: Checkout repository
        uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6.1.0

      - name: Validate configuration
        run: |
          renovate-config-validator --strict renovate.json
